-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message
(
    id               VARCHAR(64) NOT NULL,
    origin           VARCHAR(64),
    text             TEXT, -- Changed CLOB to TEXT
    lang             VARCHAR(2),
    name             TEXT, -- Changed CLOB to TEXT
    url              TEXT, -- Changed CLOB to TEXT
    create_date_time TIMESTAMP,
    PRIMARY KEY (id, create_date_time)
);

-- 2. Sentiment Analysis (One-to-Many)
CREATE TABLE IF NOT EXISTS message_entity_sentiment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id       VARCHAR(64),
    msg_timestamp    TIMESTAMP NOT NULL,
    model_name       VARCHAR(255),
    sentiment_label  VARCHAR(255),
    confidence_score REAL,
    CONSTRAINT fk_sentiment_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

-- 3. Text Search Vectors (One-to-One)
CREATE TABLE IF NOT EXISTS message_entity_tsvector
(
    message_id       VARCHAR(64) PRIMARY KEY,
    msg_timestamp    TIMESTAMP NOT NULL,
    word_vector      TEXT,
    CONSTRAINT fk_tsvector_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

-- 4. Analytics Helpers
-- Note: Using gen_random_uuid() (PG 13+) and random()
CREATE OR REPLACE VIEW term_frequency_entity_day AS
SELECT
    ROW_NUMBER() OVER (ORDER BY create_date_time) AS rank,
    LEFT(CAST(gen_random_uuid() AS VARCHAR), 8)   AS term,
    CAST(random() * 1000 AS INT)                  AS count
FROM social_message
ORDER BY create_date_time
LIMIT 1000;

CREATE OR REPLACE VIEW term_frequency_entity_week AS
SELECT
    ROW_NUMBER() OVER (ORDER BY create_date_time) AS rank,
    LEFT(CAST(gen_random_uuid() AS VARCHAR), 8)   AS term,
    CAST(random() * 1000 AS INT)                  AS count
FROM social_message
ORDER BY create_date_time
LIMIT 1000;

CREATE OR REPLACE VIEW term_frequency_entity_month AS
SELECT
    ROW_NUMBER() OVER (ORDER BY create_date_time) AS rank,
    LEFT(CAST(gen_random_uuid() AS VARCHAR), 8)   AS term,
    CAST(random() * 1000 AS INT)                  AS count
FROM social_message
ORDER BY create_date_time
LIMIT 1000;

--- 5. Vector Store
-- Note: Postgres supports JSONB natively, no need to CREATE TYPE
CREATE TABLE IF NOT EXISTS vector_store
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id    VARCHAR(64) UNIQUE,
    msg_timestamp TIMESTAMP NOT NULL,
    metadata      JSONB,
    embedding     REAL[], -- Postgres native array syntax
    CONSTRAINT fk_vector_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

--- 6. Gis Info
CREATE TABLE IF NOT EXISTS gis_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id    VARCHAR(64) UNIQUE,
    msg_timestamp TIMESTAMP NOT NULL,
    srid          INTEGER,
    gis           TEXT, -- Changed CLOB to TEXT
    geom          VARCHAR(64),
    reason        TEXT, -- Changed CLOB to TEXT
    CONSTRAINT fk_gis_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

--- 7. Timeseries DB
-- H2 Java Alias removed. Postgres supports DATE_TRUNC natively.
CREATE OR REPLACE VIEW hourly_message_stats AS
SELECT
    DATE_TRUNC('HOUR', create_date_time) AS bucket,
    origin,
    COUNT(*) AS message_count
FROM
    social_message
GROUP BY
    bucket,
    origin;

--- 8. Stock price view
-- Fixed DATEADD syntax to Postgres Interval syntax
CREATE OR REPLACE VIEW daily_stock_metrics AS
SELECT
    CAST(create_date_time AS DATE) AS bucket,
    'AVGO' AS ticker,
    AVG(CAST((text::jsonb->>'price') AS FLOAT)) AS avg_price
FROM social_message
WHERE create_date_time > (CURRENT_TIMESTAMP - INTERVAL '1 year')
  AND origin = 'stocksprice'
  AND text::jsonb->>'ticker' = 'AVGO'
GROUP BY bucket, ticker
ORDER BY bucket DESC;

-- 9. Analysis Table
CREATE TABLE IF NOT EXISTS social_message_analysis (
    message_id       VARCHAR(64) NOT NULL,
    origin           VARCHAR(64),
    url              TEXT,
    text             TEXT,
    sentiment_label  VARCHAR(20),
    confidence_score REAL,
    centroid_cluster_id INTEGER,
    geom        VARCHAR(100),
    create_date_time TIMESTAMP NOT NULL,
    PRIMARY KEY (message_id, create_date_time)
);