CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS plpython3u;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message (
    id               VARCHAR(64),
    origin           VARCHAR(64),
    text             TEXT,
    lang             VARCHAR(2),
    name             TEXT,
    url              TEXT,
    create_date_time TIMESTAMP NOT NULL,
    PRIMARY KEY (id, create_date_time) -- PK must include the time column for Hypertables
);

-- 2. Sentiment Analysis (One-to-Many)
CREATE TABLE IF NOT EXISTS message_entity_sentiment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id       VARCHAR(64),
    model_name       VARCHAR(255),
    sentiment_label  VARCHAR(255),
    confidence_score REAL,
    CONSTRAINT fk_sentiment_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

-- 3. Text Search Vectors (One-to-One)
CREATE TABLE IF NOT EXISTS message_entity_tsvector
(
    message_id  VARCHAR(64) PRIMARY KEY,
    word_vector TSVECTOR,
    CONSTRAINT fk_tsvector_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

-- 4. Analytics Helpers
CREATE MATERIALIZED VIEW term_frequency_entity AS
SELECT ROW_NUMBER() OVER (ORDER BY nentry DESC) AS rank,
       word AS term,
       nentry AS count
FROM ts_stat('SELECT word_vector FROM message_entity_tsvector')
ORDER BY nentry DESC;

--- 5. Vector Store
CREATE TABLE IF NOT EXISTS vector_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) UNIQUE,
    content    TEXT,
    metadata   JSONB,  -- JSONB is faster and supports indexing better than JSON
    embedding  REAL[], -- Postgres uses the [] syntax for arrays
    CONSTRAINT fk_vector_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

--- 6. Gis Info
CREATE TABLE IF NOT EXISTS gis_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) UNIQUE,
    srid       INTEGER DEFAULT 4326,
    gis        TEXT, -- Your existing POINT(lon lat) strings
    reason     TEXT,

    -- AUTOMATION: This column converts the 'gis' text into a real geometry
    -- It updates automatically whenever the 'gis' text changes.
    geom       GEOMETRY(Point, 4326) GENERATED ALWAYS AS (
        ST_GeomFromText(gis, 4326)
        ) STORED,

    CONSTRAINT fk_gis_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

--- 7. Timeseries DB
-- Convert to Hypertable
SELECT create_hypertable('social_message', 'create_date_time', if_not_exists => TRUE);
CREATE MATERIALIZED VIEW hourly_stock_stats
SELECT
    time_bucket_gapfill('1 hour', create_date_time) AS bucket,
    origin,
    COUNT(*) AS message_count
FROM
    social_message
WHERE
    create_date_time >= now() - INTERVAL '1 month' -- Gapfill requires a time range
GROUP BY
    bucket,
    origin
ORDER BY
    bucket DESC;

--- 8. Stock price view
SELECT
    time_bucket_gapfill('1 day', create_date_time) AS day,
    ticker,
    -- locf (Last Observation Carried Forward) fills nulls with the previous day's price
    locf(AVG(price)) AS avg_daily_price,
    COALESCE(SUM(volume), 0) AS total_daily_volume
FROM
    social_message
WHERE
    create_date_time >= NOW() - INTERVAL '1 month'
    AND create_date_time < NOW()
    AND origin = 'stocksprice'
GROUP BY
    day, ticker
ORDER BY
    day DESC;

-- Recommended Indexes for Analytics Performance
CREATE INDEX IF NOT EXISTS idx_sentiment_lookup ON message_entity_sentiment (message_id, model_name);
CREATE INDEX IF NOT EXISTS idx_tsvector_gin ON message_entity_tsvector USING GIN(word_vector);
CREATE INDEX IF NOT EXISTS idx_term_freq_term ON term_frequency_entity (term);
CREATE INDEX IF NOT EXISTS idx_gis_info_spatial ON gis_info USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_vector_search ON vector_store USING hnsw (embedding vector_cosine_ops);