CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS plpython3u;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message
(
    id               VARCHAR(64) PRIMARY KEY,
    origin           VARCHAR(64),
    text             TEXT,
    lang             VARCHAR(2),
    name             TEXT,
    url              TEXT,
    create_date_time TIMESTAMP
);

-- 2. Sentiment Analysis (One-to-Many)
CREATE TABLE IF NOT EXISTS message_entity_sentiment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id       VARCHAR(64),
    model_name       VARCHAR(255),
    sentiment_label  VARCHAR(255),
    confidence_score REAL,
    CONSTRAINT fk_sentiment_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

-- 3. Text Search Vectors (One-to-One)
CREATE TABLE IF NOT EXISTS message_entity_tsvector
(
    message_id  VARCHAR(64) PRIMARY KEY,
    word_vector TSVECTOR,
    CONSTRAINT fk_tsvector_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

-- 4. Analytics Helpers
-- Postgres allows ORDER BY and LIMIT in Views
CREATE MATERIALIZED VIEW term_frequency_entity AS
SELECT ROW_NUMBER() OVER (ORDER BY nentry DESC) AS rank,
       word AS term,
       nentry AS count
FROM ts_stat('SELECT word_vector FROM message_entity_tsvector')
ORDER BY nentry DESC;

--- 5. Vector Store
CREATE TABLE IF NOT EXISTS vector_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) UNIQUE,
    content    TEXT,
    metadata   JSONB,  -- JSONB is faster and supports indexing better than JSON
    embedding  REAL[], -- Postgres uses the [] syntax for arrays
    CONSTRAINT fk_vector_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

--- 6. Gis Info
CREATE TABLE IF NOT EXISTS gis_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) UNIQUE,
    srid       INTEGER DEFAULT 4326,
    gis        TEXT, -- Your existing POINT(lon lat) strings
    reason     TEXT,

    -- AUTOMATION: This column converts the 'gis' text into a real geometry
    -- It updates automatically whenever the 'gis' text changes.
    geom       GEOMETRY(Point, 4326) GENERATED ALWAYS AS (
        ST_GeomFromText(gis, 4326)
        ) STORED,

    CONSTRAINT fk_gis_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
            ON DELETE CASCADE
);

-- Recommended Indexes for Analytics Performance
CREATE INDEX IF NOT EXISTS idx_sentiment_lookup ON message_entity_sentiment (message_id, model_name);
CREATE INDEX IF NOT EXISTS idx_tsvector_gin ON message_entity_tsvector USING GIN(word_vector);
CREATE INDEX IF NOT EXISTS idx_term_freq_term ON term_frequency_entity (term);
CREATE INDEX IF NOT EXISTS idx_gis_info_spatial ON gis_info USING GIST (geom);