CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS plpython3u;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS timescaledb;

-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message (
    id               VARCHAR(64),
    origin           VARCHAR(64),
    text             TEXT,
    lang             VARCHAR(2),
    name             TEXT,
    url              TEXT,
    create_date_time TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id, create_date_time)
);

-- Convert to Hypertable
SELECT create_hypertable('social_message', 'create_date_time', if_not_exists => TRUE);

-- 2. Sentiment Analysis
CREATE TABLE IF NOT EXISTS message_entity_sentiment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id       VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    model_name       VARCHAR(255),
    sentiment_label  VARCHAR(255),
    confidence_score REAL,
    PRIMARY KEY (id, msg_timestamp),
    CONSTRAINT fk_sentiment_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

-- 3. Text Search Vectors
CREATE TABLE IF NOT EXISTS message_entity_tsvector
(
    message_id  VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    word_vector TSVECTOR,
    PRIMARY KEY (message_id, msg_timestamp),
    CONSTRAINT fk_tsvector_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

-- 4. Analytics Helpers
CREATE MATERIALIZED VIEW IF NOT EXISTS term_frequency_entity AS
SELECT ROW_NUMBER() OVER (ORDER BY nentry DESC) AS rank,
       word AS term,
       nentry AS count
FROM ts_stat('SELECT word_vector FROM message_entity_tsvector')
ORDER BY nentry DESC;

--- 5. Vector Store
CREATE TABLE IF NOT EXISTS vector_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    metadata   JSONB,
    embedding  VECTOR(1024),
    PRIMARY KEY (id, msg_timestamp),
    CONSTRAINT fk_vector_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

--- 6. GIS Info
CREATE TABLE IF NOT EXISTS gis_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    srid       INTEGER DEFAULT 4326,
    gis        TEXT,
    reason     TEXT,
    geom       GEOMETRY(Point, 4326) GENERATED ALWAYS AS (
        ST_GeomFromText(gis, 4326)
        ) STORED,
    PRIMARY KEY (id, msg_timestamp),
    CONSTRAINT fk_gis_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

--- 7. Aggregation Layer
CREATE MATERIALIZED VIEW IF NOT EXISTS hourly_message_stats
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 hour', create_date_time) AS bucket,
    origin,
    COUNT(*) AS message_count
FROM social_message
GROUP BY bucket, origin;

-- Set refresh policy
SELECT add_continuous_aggregate_policy('hourly_message_stats',
    start_offset => INTERVAL '1 month',
    end_offset => INTERVAL '6 hours',
    schedule_interval => INTERVAL '30 minutes');

-- -- Gapfill View (Standard View)
-- CREATE OR REPLACE VIEW hourly_message_gapfill AS
-- SELECT
--     time_bucket_gapfill('1 hour', bucket) AS hour,
--     origin,
--     COALESCE(SUM(message_count), 0) AS message_count
-- FROM hourly_message_stats
-- WHERE bucket >= now() - INTERVAL '1 month'
--   AND bucket < now()
-- GROUP BY hour, origin;

--- 8. Continuous Aggregate for Stock price
CREATE MATERIALIZED VIEW IF NOT EXISTS daily_stock_metrics
WITH (timescaledb.continuous) AS
SELECT
    time_bucket('1 day', create_date_time) AS bucket,
    (text::jsonb) ->> 'ticker' AS ticker,
    AVG(((text::jsonb) ->> 'price')::NUMERIC) AS avg_price,
    SUM(((text::jsonb) ->> 'volume')::BIGINT) AS total_volume
FROM
    social_message
WHERE
    origin = 'stocksprice'
GROUP BY
    bucket, ticker;

-- Set refresh policy
SELECT add_continuous_aggregate_policy('daily_stock_metrics',
    start_offset => INTERVAL '1 month',
    end_offset => INTERVAL '1 hour',
    schedule_interval => INTERVAL '6 hours');

-- Recommended Indexes
CREATE INDEX IF NOT EXISTS idx_social_message_origin ON social_message (origin, create_date_time DESC);
CREATE INDEX IF NOT EXISTS idx_sentiment_lookup ON message_entity_sentiment (message_id, model_name);
CREATE INDEX IF NOT EXISTS idx_tsvector_gin ON message_entity_tsvector USING GIN(word_vector);
CREATE INDEX IF NOT EXISTS idx_gis_info_spatial ON gis_info USING GIST (geom);
CREATE INDEX IF NOT EXISTS idx_vector_search ON vector_store USING hnsw (embedding vector_cosine_ops);