CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS plpython3u;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message (
    id               VARCHAR(64),
    origin           VARCHAR(64),
    text             TEXT,
    lang             VARCHAR(2),
    name             TEXT,
    url              TEXT,
    create_date_time TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id, create_date_time)
)
WITH (
    appendonly = true,
    orientation = column,
    compresstype = zstd,
    compresslevel = 3
)
DISTRIBUTED BY (id)
PARTITION BY RANGE (create_date_time)
(
    DEFAULT PARTITION other
);


-- 2. Sentiment Analysis (Distributed by message_id to co-locate with social_message)
CREATE TABLE IF NOT EXISTS message_entity_sentiment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id       VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    model_name       VARCHAR(255),
    sentiment_label  VARCHAR(255),
    confidence_score REAL,
    PRIMARY KEY (message_id, msg_timestamp)
)
WITH (
    appendonly = true,
    orientation = column,
    compresstype = zstd,
    compresslevel = 3
)
DISTRIBUTED BY (message_id);

-- 3. Text Search Vectors
CREATE TABLE IF NOT EXISTS message_entity_tsvector
(
    message_id  VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    word_vector TSVECTOR,
    PRIMARY KEY (message_id, msg_timestamp)
)
WITH (
    appendonly = true,
    orientation = column,
    compresstype = zstd,
    compresslevel = 3
)
DISTRIBUTED BY (message_id);

-- 4. Analytics Helpers
CREATE OR REPLACE VIEW term_frequency_entity_month  AS
SELECT ROW_NUMBER() OVER (ORDER BY nentry DESC) AS rank,
       word AS term,
       nentry AS count
FROM ts_stat('SELECT word_vector FROM message_entity_tsvector WHERE msg_timestamp >= CURRENT_DATE - INTERVAL ''1 month''')
ORDER BY nentry DESC;

CREATE OR REPLACE VIEW term_frequency_entity_week  AS
SELECT ROW_NUMBER() OVER (ORDER BY nentry DESC) AS rank,
       word AS term,
       nentry AS count
FROM ts_stat('SELECT word_vector FROM message_entity_tsvector WHERE msg_timestamp >= CURRENT_DATE - INTERVAL ''1 week''')
ORDER BY nentry DESC;

CREATE OR REPLACE VIEW term_frequency_entity_day AS
SELECT ROW_NUMBER() OVER (ORDER BY nentry DESC) AS rank,
       word AS term,
       nentry AS count
FROM ts_stat('SELECT word_vector FROM message_entity_tsvector WHERE msg_timestamp >= CURRENT_DATE - INTERVAL ''1 day''')
ORDER BY nentry DESC;

--- 5. Vector Store
CREATE TABLE IF NOT EXISTS vector_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    metadata   JSONB,
    embedding  VECTOR(1024),
    PRIMARY KEY (message_id, msg_timestamp)
)
WITH (
    appendonly = true,
    orientation = column,
    compresstype = zstd,
    compresslevel = 3
)
DISTRIBUTED BY (message_id);

--- 6. GIS Info
CREATE TABLE IF NOT EXISTS gis_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id VARCHAR(64),
    msg_timestamp    TIMESTAMPTZ NOT NULL,
    srid       INTEGER DEFAULT 4326,
    gis        TEXT,
    reason     TEXT,
    geom       GEOMETRY(Point, 4326) GENERATED ALWAYS AS (
        ST_GeomFromText(gis, 4326)
        ) STORED,
    PRIMARY KEY (message_id, msg_timestamp)
)
WITH (
    appendonly = true,
    orientation = column,
    compresstype = zstd,
    compresslevel = 3
)
DISTRIBUTED BY (message_id);

--- 7. Aggregation Layer
-- Greenplum 7 supports mv_maintain_mode=full
CREATE MATERIALIZED VIEW IF NOT EXISTS hourly_message_stats with(mv_maintain_mode=full) AS
SELECT
    date_trunc('hour', create_date_time) AS bucket,
    origin,
    COUNT(*) AS message_count
FROM social_message
GROUP BY bucket, origin
DISTRIBUTED BY (origin);

--- 8. Continuous Aggregate for Stock price
CREATE MATERIALIZED VIEW IF NOT EXISTS daily_stock_metrics with(mv_maintain_mode=full) AS
SELECT
    date_trunc('day', create_date_time) AS bucket,
    (text::jsonb) ->> 'ticker' AS ticker,
    AVG(((text::jsonb) ->> 'price')::NUMERIC) AS avg_price,
    SUM(((text::jsonb) ->> 'volume')::BIGINT) AS total_volume
FROM
    social_message
WHERE
    origin = 'stocksprice'
GROUP BY
    bucket, ticker
DISTRIBUTED BY (ticker);

--- Cleanup UDF since Greenplum doesn't support FK constraints
-- SELECT delete_social_message_batch(
--     ARRAY['id1', 'id2'],
--     ARRAY['2023-10-27 10:00:00+00'::timestamptz, '2023-10-27 11:00:00+00'::timestamptz]
-- );
CREATE OR REPLACE FUNCTION delete_social_message_batch(
    p_message_ids VARCHAR[],
    p_timestamps TIMESTAMPTZ[]
)
RETURNS VOID AS '
BEGIN
    -- Prerequisite: Arrays must be of equal length.
    -- We join the arrays to the tables to perform a bulk delete.

    -- 1. Delete from Sentiment
    DELETE FROM message_entity_sentiment AS t
    USING unnest(p_message_ids, p_timestamps) AS input(id, ts)
    WHERE t.message_id = input.id AND t.msg_timestamp = input.ts;

    -- 2. Delete from TSVector
    DELETE FROM message_entity_tsvector AS t
    USING unnest(p_message_ids, p_timestamps) AS input(id, ts)
    WHERE t.message_id = input.id AND t.msg_timestamp = input.ts;

    -- 3. Delete from Vector Store
    DELETE FROM vector_store AS t
    USING unnest(p_message_ids, p_timestamps) AS input(id, ts)
    WHERE t.message_id = input.id AND t.msg_timestamp = input.ts;

    -- 4. Delete from GIS Info
    DELETE FROM gis_info AS t
    USING unnest(p_message_ids, p_timestamps) AS input(id, ts)
    WHERE t.message_id = input.id AND t.msg_timestamp = input.ts;

    -- 5. Delete from Parent
    DELETE FROM social_message AS t
    USING unnest(p_message_ids, p_timestamps) AS input(id, ts)
    WHERE t.id = input.id AND t.create_date_time = input.ts;

END;
' LANGUAGE plpgsql;

-- Greenplum does not enforce indexes by default, so not creating thme
-- CREATE INDEX IF NOT EXISTS idx_social_message_origin ON social_message (origin, create_date_time DESC);
-- CREATE INDEX IF NOT EXISTS idx_sentiment_lookup ON message_entity_sentiment (message_id, model_name);
-- CREATE INDEX IF NOT EXISTS idx_tsvector_gin ON message_entity_tsvector USING GIN(word_vector);
-- CREATE INDEX IF NOT EXISTS idx_gis_info_spatial ON gis_info USING GIST (geom);
-- CREATE INDEX IF NOT EXISTS idx_vector_search ON vector_store USING hnsw (embedding vector_cosine_ops);