-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message (
    id                VARCHAR(64) NOT NULL,
    origin            VARCHAR(64),
    text              TEXT,
    lang              VARCHAR(10), -- Increased to 10 to support tags like 'en-US'
    name              TEXT,
    url               TEXT,
    create_date_time  TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id)
);

-- 2. Sentiment Analysis (One-to-Many)
CREATE TABLE IF NOT EXISTS message_entity_sentiment (
    -- PostgreSQL uses 'GENERATED ... AS IDENTITY' instead of AUTO_INCREMENT
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    message_id        VARCHAR(64),
    model_name        VARCHAR(255),
    sentiment_label   VARCHAR(255),
    confidence_score  REAL, -- 'REAL' is the standard 4-byte float in Postgres
    PRIMARY KEY (id),
    CONSTRAINT fk_sentiment_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
        ON DELETE CASCADE
);

-- 3. Text Search Vectors (One-to-One)
CREATE TABLE IF NOT EXISTS message_entity_tsvector (
    message_id        VARCHAR(64) PRIMARY KEY, -- Added PRIMARY KEY
    word_vector       TSVECTOR, -- Changed from TEXT to native PostgreSQL search type
    CONSTRAINT fk_tsvector_message
        FOREIGN KEY (message_id) REFERENCES social_message (id)
        ON DELETE CASCADE
);

-- 4. Analytics Helpers
CREATE TABLE IF NOT EXISTS term_frequency_entity (
    rank              INTEGER NOT NULL,
    term              VARCHAR(255) NOT NULL,
    count             INTEGER DEFAULT 0
);

-- Recommended Indexes for Analytics Performance
CREATE INDEX IF NOT EXISTS idx_sentiment_lookup ON message_entity_sentiment(message_id, model_name);
CREATE INDEX IF NOT EXISTS idx_tsvector_gin ON message_entity_tsvector USING GIN(word_vector);