-- 1. Main Message Table
CREATE TABLE IF NOT EXISTS social_message
(
    id               VARCHAR(64) NOT NULL,
    origin           VARCHAR(64),
    text             CHARACTER LARGE OBJECT, -- Using CLOB for compatibility
    lang             VARCHAR(2),
    name             CHARACTER LARGE OBJECT,
    url              CHARACTER LARGE OBJECT,
    create_date_time TIMESTAMP,
    PRIMARY KEY (id, create_date_time)
);

-- 2. Sentiment Analysis (One-to-Many)
CREATE TABLE IF NOT EXISTS message_entity_sentiment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id       VARCHAR(64),
    msg_timestamp    TIMESTAMP NOT NULL,
    model_name       VARCHAR(255),
    sentiment_label  VARCHAR(255),
    confidence_score REAL, -- Changed for standard H2 real type
    CONSTRAINT fk_sentiment_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

-- 3. Text Search Vectors (One-to-One)
CREATE TABLE IF NOT EXISTS message_entity_tsvector
(
    message_id  VARCHAR(64) PRIMARY KEY,
    msg_timestamp    TIMESTAMP NOT NULL,
    word_vector CHARACTER LARGE OBJECT,
    CONSTRAINT fk_tsvector_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

-- 4. Analytics Helpers
-- Note: ROW_NUMBER() and LIMIT are now correctly ordered for H2
CREATE VIEW IF NOT EXISTS term_frequency_entity
AS
SELECT
    ROW_NUMBER() OVER (ORDER BY create_date_time) AS rank,
    LEFT(CAST(RANDOM_UUID() AS VARCHAR), 8)       AS term,
    CAST(RAND() * 1000 AS INT)                    AS count
FROM social_message
ORDER BY create_date_time
LIMIT 1000;

--- 5. Vector Store
CREATE TYPE IF NOT EXISTS "JSONB" AS json;
CREATE TABLE IF NOT EXISTS vector_store
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) UNIQUE,
    msg_timestamp    TIMESTAMP NOT NULL,
    metadata   JSONB, -- Works in H2 2.x+
    embedding  REAL ARRAY, -- H2 supports ARRAY types natively
    CONSTRAINT fk_vector_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

--- 6. Gis Info
CREATE TABLE IF NOT EXISTS gis_info
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(64) UNIQUE,
    msg_timestamp    TIMESTAMP NOT NULL,
    srid       INTEGER,
    gis        CHARACTER LARGE OBJECT,
    reason     CHARACTER LARGE OBJECT,
    CONSTRAINT fk_gis_message
        FOREIGN KEY (message_id, msg_timestamp) REFERENCES social_message (id, create_date_time)
            ON DELETE CASCADE
);

--- 7. Timeseries DB
CREATE ALIAS IF NOT EXISTS time_bucket AS '
import java.sql.Timestamp;
import java.time.temporal.ChronoUnit;
@CODE
Timestamp timeBucket(String bucket_width, Timestamp ts) {
    long ms = ts.getTime();
    if (bucket_width.equalsIgnoreCase("1 hour")) {
        return new Timestamp((ms / 3600000) * 3600000);
    }
    return ts; // Fallback
}
';
-- Standard View for H2 testing
CREATE VIEW IF NOT EXISTS hourly_message_stats AS
SELECT
    DATE_TRUNC('HOUR', create_date_time) AS bucket,
    origin,
    COUNT(*) AS message_count
FROM
    social_message
GROUP BY
    bucket,
    origin;

--- 8. Stock price view
CREATE VIEW IF NOT EXISTS daily_stock_view AS
SELECT
    CAST(create_date_time AS DATE) AS report_day,
    'AVGO' AS ticker,
    '500' AS avg_price
FROM social_message
WHERE create_date_time > DATEADD('MONTH', -1, CURRENT_TIMESTAMP)
  AND origin = 'stocksprice'
GROUP BY report_day, ticker
ORDER BY report_day DESC;